### ISSUE TITLE
how to do if I want to input a image that I take by myself?

### ISSUE THREAD

**Issue by For-thewin** [valentin-deschaintre/Single-Image-SVBRDF-Capture-rendering-loss#1]
`           Hello, thanks for your project. I had run the test examples successsfully and it worked well. But now i want to get the result of my own test image, which seems to be wrong if i just add the picture to the imput dir directly. So I need to train for my own test image and then I can get the reuslts?  I am looking forward to your reply. Thx.`

**Comment by valentin-deschaintre** [comment]
Hello,

You should not have to retrain. The network by default processes linear images (and outputs linear albedos). So if your image comes directly from your phone for example, you would have to linearize the image. 
In this version of the code I added an option so that it is done by the preprocessing step. You can add "--correctGamma" to correct the input image from a gamma 2.2 to a linear image (the images in the test folder are already linear so this would produce wrong results for these).

The network I provide is trained on flash centered pictures of size 256x256, so if you change one of these parameters it will not behave a expected.
Despite it being fully convolutional, the results degrade in quality with higher res as we show in the supplemental of another paper (which you can use if you need higher resolution or scale): https://team.inria.fr/graphdeco/projects/large-scale-materials/.

**Comment by For-thewin** [comment]
Thanks for your help and I get the results successfully. This network works very well. And I will continue following with interest on your research, Thanks again!

**Comment by valentin-deschaintre** [comment]
Thank you very much, if you are curious about how to get HD results or capture larger surfaces, please check our latest paper: https://team.inria.fr/graphdeco/projects/large-scale-materials/
